name: Build Android & iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn test --ci

  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v3
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - run: yarn install --frozen-lockfile

      - run: pod install
        working-directory: ios

      # Archive the app
      - run: xcodebuild clean archive -workspace testCiCdReactNative.xcworkspace -scheme testCiCdReactNative -archivePath testCiCdReactNative.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
        working-directory: ios

      # Export the archive to an IPA file
      - run: xcodebuild -exportArchive -archivePath testCiCdReactNative.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath ./build
        working-directory: ios

      # Upload the IPA file as an artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: Ipa
          path: ios/build/*.ipa

  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: yarn install --frozen-lockfile

      - name: Bundle *.aap & *.apk
        run: cd android && ./gradlew bundleRelease assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Aab
          path: android/app/build/outputs/bundle/release/app-release.aab
